### ISSUE TITLE
FC issue

### ISSUE THREAD

**Issue by chenshengfa0803** [chenshengfa1990/BookStore#2]
06-16 20:22:50.145  9539  9539 D AndroidRuntime: Shutting down VM
06-16 20:22:50.145  9539  9539 E AndroidRuntime: FATAL EXCEPTION: main
06-16 20:22:50.145  9539  9539 E AndroidRuntime: Process: com.bookstore.main, PID: 9539
06-16 20:22:50.145  9539  9539 E AndroidRuntime: java.lang.IllegalStateException: Fragment MainBookListFragment{dba6d6e} not attached to Activity
06-16 20:22:50.145  9539  9539 E AndroidRuntime:    at android.support.v4.app.Fragment.getResources(Fragment.java:620)
06-16 20:22:50.145  9539  9539 E AndroidRuntime:    at com.bookstore.main.MainBookListFragment.updateFloatButton(MainBookListFragment.java:451)
06-16 20:22:50.145  9539  9539 E AndroidRuntime:    at com.bookstore.main.MainBookListFragment$7.done(MainBookListFragment.java:410)
06-16 20:22:50.145  9539  9539 E AndroidRuntime:    at com.avos.avoscloud.FindCallback.internalDone0(FindCallback.java:37)
06-16 20:22:50.145  9539  9539 E AndroidRuntime:    at com.avos.avoscloud.FindCallback.internalDone0(FindCallback.java:27)
06-16 20:22:50.145  9539  9539 E AndroidRuntime:    at com.avos.avoscloud.AVCallback$1.run(AVCallback.java:12)
06-16 20:22:50.145  9539  9539 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:739)
06-16 20:22:50.145  9539  9539 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:95)
06-16 20:22:50.145  9539  9539 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:148)
06-16 20:22:50.145  9539  9539 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:7325)
06-16 20:22:50.145  9539  9539 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
06-16 20:22:50.145  9539  9539 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
06-16 20:22:50.145  9539  9539 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by chenshengfa0803** [comment]
if (mActivity.isDestroyed()) {
                                    return;
                                }
